version: '3.8'
services:
  # redis:
  # image: redis
  # ports:
  #   - "6379:6379"
  # networks:
  #   - CDDAdb-network
  play:
    # depends_on:
    #  - redis
    build: .
    image: cddadb:latest
    ports:
      - "9000:9000"
    networks:
      - CDDAdb-network
    volumes:
      - "~/cddadb-conf:/cddadb-conf"
networks:
  CDDAdb-network: